### ISSUE TITLE
Add git-patch icon

### ISSUE THREAD

**Issue by ligaz** [github/octicons#43]
A common use case is to visual patches so having a patch icon will be a great addition.

**Comment by jglovier** [comment]
@ligaz can you explain a little further the use cases you have in mind?

**Comment by ligaz** [comment]
Hey @jglovier 

There are two use cases that I can point to:
* Icon for [TortoiseGit](https://code.google.com/p/tortoisegit/)
* Icon for Telerik AppBuilder. We are currently using a couple of the Octicons there.

**Comment by jglovier** [comment]
Per @cameronmcefee's [comment](https://github.com/github/octicons/issues/44#issuecomment-85067253) in #44, we add icons as they are needed for our own purposes rather than by request, since our goal is a GitHub set rather than a fully featured one like may of the great ones out there already. 

Since Git patching isn't a feature currently supported in the GitHub Desktop apps, or the .com workflow, this isn't one we currently have a good reason to add. 

Thanks for the suggestion. :heart: I'll reopen if we decide to add it in the future.
