### ISSUE TITLE
Operating system icons

### ISSUE THREAD

**Issue by xPaw** [github/octicons#44]
Would it be out of scope for this project to have OS icons (primarily windows/osx/linux)?

GitHub itself could potentially display them in session list here: https://github.com/settings/security

**Comment by cameronmcefee** [comment]
So far we've not included them to avoid Terms of Use issues. Beyond the question of whether we have the right to distribute the logos in the font, each logo has it's own strict usage guidelines which can't be bundled in or enforced.

From my personal perspective, Octicons is purely a GitHub tool which we've made accessible and easier to use for the public since everyone was already ripping it out of the site anyway. We add icons as they are needed for our own purposes rather than by request, since our goal is a GitHub set rather than a fully featured one like may of the great ones out there already. Given that background, including the OS logos requires us to educate every GitHub employee who might include the logo somewhere on the individual logo usage guides which isn't the easiest process. It's something we've gone back and forth on but for the moment we're on the no-trademarked-logos side of the fence.

Also it was impossible to make the Windows logo look good on Windows due to the font smoothing, an irony which drove me bonkers.

**Comment by cameronmcefee** [comment]
It's worth noting that the Octicons license (OFL) permits de/recompiling, should you wish to append your own icons.
