### ISSUE TITLE
Create separate icons for PR states

### ISSUE THREAD

**Issue by pyhedgehog** [github/octicons#69]
Currently there are single icon for "open", "closed" and "merged" states of PR.
It's not working when line with icon is "disabled" (see GitHubHQ/Project#1).
Also it may be problem with bad colour transfers (b/w device and so on).

**Comment by cameronmcefee** [comment]
Hi @pyhedgehog,

The single icon is by design. We originally had mixed states, but at the small size they weren't very distinguishable. Our policy is to use one icon to set the context and additional elements such as text labels and colors to express the state. Issues is an outlier, as you point out, but we will not be creating future stateful icons.

**Comment by pyhedgehog** [comment]
Your design is beautiful, but what about [WAI](https://en.wikipedia.org/wiki/Web_accessibility)/[CB](https://en.wikipedia.org/wiki/Color_blindness)?
